import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigration1754887880050 implements MigrationInterface {
    name = 'InitialMigration1754887880050'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "amenities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying(100) NOT NULL, "category" character varying NOT NULL, "description" text, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_8c5f9c7ff7e2174b53d4be10247" UNIQUE ("name"), CONSTRAINT "PK_c0777308847b3556086f2fb233e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8020b0d3a0e19f06464c2a9d0b" ON "amenities" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_1310fb8b8ec62a1f5292f49e1b" ON "amenities" ("category") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8c5f9c7ff7e2174b53d4be1024" ON "amenities" ("name") `);
        await queryRunner.query(`CREATE TABLE "room_amenities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "room_id" uuid NOT NULL, "amenity_id" uuid NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "installed_date" date, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3812057aa7d58f8f6dd349c622e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "room_occupants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "room_id" uuid NOT NULL, "student_id" uuid NOT NULL, "check_in_date" date NOT NULL, "check_out_date" date, "bed_number" character varying, "status" character varying(20) NOT NULL DEFAULT 'Active', "notes" text, "assigned_by" character varying(100), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f9ac871cdda9d5980c6839e2104" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "room_layouts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "room_id" uuid NOT NULL, "layout_type" character varying(50) NOT NULL DEFAULT 'standard', "layoutData" jsonb, "bedPositions" jsonb, "furnitureLayout" jsonb, "dimensions" jsonb, "floorPlan" jsonb, "is_active" boolean NOT NULL DEFAULT true, "created_by" character varying(100), "updated_by" character varying(100), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_6c9f060b1d7c9756a8b60a6a614" UNIQUE ("room_id"), CONSTRAINT "REL_6c9f060b1d7c9756a8b60a6a61" UNIQUE ("room_id"), CONSTRAINT "PK_3dadc9ff0546b5489cecce89129" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "buildings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying(255) NOT NULL, "address" text, "floors" integer, "totalRooms" integer, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_3f5a7e0aabca27edc3806fdb298" UNIQUE ("name"), CONSTRAINT "PK_bc65c1acce268c383e41a69003a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3f5a7e0aabca27edc3806fdb29" ON "buildings" ("name") `);
        await queryRunner.query(`CREATE TABLE "room_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying(100) NOT NULL, "description" text, "baseMonthlyRate" numeric(10,2), "baseDailyRate" numeric(10,2), "defaultBedCount" integer, "maxOccupancy" integer, "pricingModel" character varying, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_20180102ff8f034e54c5812f695" UNIQUE ("name"), CONSTRAINT "PK_b6e1d0a9b67d4b9fbff9c35ab69" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5457ff4ea3051ac9ad68969f5f" ON "room_types" ("isActive") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_20180102ff8f034e54c5812f69" ON "room_types" ("name") `);
        await queryRunner.query(`CREATE TABLE "rooms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying(255) NOT NULL, "roomNumber" character varying(20) NOT NULL, "bedCount" integer NOT NULL DEFAULT '1', "occupancy" integer NOT NULL DEFAULT '0', "gender" character varying, "status" character varying NOT NULL, "maintenanceStatus" character varying, "lastCleaned" TIMESTAMP, "lastMaintenance" TIMESTAMP, "description" text, "buildingId" uuid, "roomTypeId" uuid, CONSTRAINT "UQ_e38efca75345af077ed83d53b6f" UNIQUE ("roomNumber"), CONSTRAINT "PK_0368a2d7c215f2d0458a54933f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ed601f2a18a58e7bb5093ce7e3" ON "rooms" ("gender") `);
        await queryRunner.query(`CREATE INDEX "IDX_76b20e23154532d6fc4a0f0ea2" ON "rooms" ("roomTypeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0390a2fda90b13e8f578ff920c" ON "rooms" ("buildingId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ffd12d5e703ed4027ebd41df44" ON "rooms" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e38efca75345af077ed83d53b6" ON "rooms" ("roomNumber") `);
        await queryRunner.query(`CREATE TYPE "public"."booking_requests_status_enum" AS ENUM('Pending', 'Approved', 'Rejected', 'Cancelled', 'Expired')`);
        await queryRunner.query(`CREATE TABLE "booking_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying(255) NOT NULL, "phone" character varying(20) NOT NULL, "email" character varying(255) NOT NULL, "guardian_name" character varying(255), "guardian_phone" character varying(20), "preferred_room" character varying(255), "course" character varying(255), "institution" character varying(255), "request_date" date NOT NULL, "check_in_date" date, "duration" character varying(50), "status" "public"."booking_requests_status_enum" NOT NULL DEFAULT 'Pending', "notes" text, "emergency_contact" character varying(20), "address" text, "id_proof_type" character varying(50), "id_proof_number" character varying(100), "approved_date" date, "processed_by" character varying(100), "rejection_reason" text, "assigned_room" character varying(50), "priority_score" integer NOT NULL DEFAULT '0', "source" character varying(50) NOT NULL DEFAULT 'website', CONSTRAINT "PK_62c29ee249979fe0bcdcde33dae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_74e588ac3c9e2ac2a5b557cfaa" ON "booking_requests" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_edc5f87424722536e690051bd5" ON "booking_requests" ("phone") `);
        await queryRunner.query(`CREATE INDEX "IDX_c2e6a2eac7e1f90103491f3001" ON "booking_requests" ("check_in_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_0567a1c8478376a332de21ef4e" ON "booking_requests" ("request_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_820acb1f1d89fd9085a4204274" ON "booking_requests" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."invoice_items_category_enum" AS ENUM('Accommodation', 'Services', 'Food', 'Utilities', 'Other')`);
        await queryRunner.query(`CREATE TABLE "invoice_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "invoice_id" uuid NOT NULL, "description" character varying(255) NOT NULL, "amount" numeric(10,2) NOT NULL, "category" "public"."invoice_items_category_enum" NOT NULL DEFAULT 'Other', "quantity" integer NOT NULL DEFAULT '1', "unit_price" numeric(10,2), "tax_rate" numeric(5,2) NOT NULL DEFAULT '0', "tax_amount" numeric(10,2) NOT NULL DEFAULT '0', "is_taxable" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_53b99f9e0e2945e69de1a12b75a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2a6bd669a5ce3579b7f751afb9" ON "invoice_items" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_dc991d555664682cfe892eea2c" ON "invoice_items" ("invoice_id") `);
        await queryRunner.query(`CREATE TYPE "public"."payments_payment_method_enum" AS ENUM('Cash', 'Bank Transfer', 'Card', 'Online', 'Cheque', 'UPI', 'Mobile Wallet')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('Completed', 'Pending', 'Failed', 'Cancelled', 'Refunded')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "student_id" uuid NOT NULL, "amount" numeric(10,2) NOT NULL, "payment_method" "public"."payments_payment_method_enum" NOT NULL, "payment_date" date NOT NULL, "reference" character varying(255), "notes" text, "status" "public"."payments_status_enum" NOT NULL DEFAULT 'Completed', "transaction_id" character varying(255), "receipt_number" character varying(100), "processed_by" character varying(100) NOT NULL DEFAULT 'admin', "bank_name" character varying(100), "cheque_number" character varying(50), "cheque_date" date, CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_28a497308e609408717dadf192" ON "payments" ("amount") `);
        await queryRunner.query(`CREATE INDEX "IDX_32b41cdb985a296213e9a928b5" ON "payments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_3f65f62084af2ebfbe39f8955b" ON "payments" ("payment_method") `);
        await queryRunner.query(`CREATE INDEX "IDX_685fffacc6464277439d0260ab" ON "payments" ("payment_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_9fd5d6ef620b0140a67ff2d95c" ON "payments" ("student_id") `);
        await queryRunner.query(`CREATE TABLE "payment_invoice_allocations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "payment_id" uuid NOT NULL, "invoice_id" uuid NOT NULL, "allocated_amount" numeric(10,2) NOT NULL, "allocation_date" date NOT NULL DEFAULT ('now'::text)::date, "allocated_by" character varying(100) NOT NULL DEFAULT 'system', "notes" text, CONSTRAINT "PK_597b92c8b52ace89ff0dd1b4376" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b5a8a2c5db43abdee5ce5f1441" ON "payment_invoice_allocations" ("invoice_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_76537e5e10deb46e527c75af62" ON "payment_invoice_allocations" ("payment_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_adac6477f8ae75b75d47d77279" ON "payment_invoice_allocations" ("payment_id", "invoice_id") `);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('Paid', 'Unpaid', 'Partially Paid', 'Overdue', 'Cancelled')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "student_id" uuid NOT NULL, "month" character varying(7) NOT NULL, "total" numeric(10,2) NOT NULL DEFAULT '0', "status" "public"."invoices_status_enum" NOT NULL DEFAULT 'Unpaid', "due_date" date NOT NULL, "subtotal" numeric(10,2) NOT NULL DEFAULT '0', "discount_total" numeric(10,2) NOT NULL DEFAULT '0', "payment_total" numeric(10,2) NOT NULL DEFAULT '0', "notes" text, "invoice_number" character varying(50), "generated_by" character varying(100) NOT NULL DEFAULT 'system', CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0457ee681a50419881ea2ee796" ON "invoices" ("due_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_ac0f09364e3701d9ed35435288" ON "invoices" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_e1ba9929f00a8e2ee0ca1e30b8" ON "invoices" ("month") `);
        await queryRunner.query(`CREATE INDEX "IDX_0a19069218ffe36a4e4b41c487" ON "invoices" ("student_id") `);
        await queryRunner.query(`CREATE TYPE "public"."ledger_entries_type_enum" AS ENUM('Invoice', 'Payment', 'Discount', 'Adjustment', 'Refund', 'Penalty', 'Credit Note', 'Debit Note')`);
        await queryRunner.query(`CREATE TYPE "public"."ledger_entries_balance_type_enum" AS ENUM('Dr', 'Cr', 'Nil')`);
        await queryRunner.query(`CREATE TABLE "ledger_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "student_id" uuid NOT NULL, "date" date NOT NULL, "type" "public"."ledger_entries_type_enum" NOT NULL, "description" text NOT NULL, "reference_id" character varying, "debit" numeric(10,2) NOT NULL DEFAULT '0', "credit" numeric(10,2) NOT NULL DEFAULT '0', "balance" numeric(10,2) NOT NULL DEFAULT '0', "balance_type" "public"."ledger_entries_balance_type_enum" NOT NULL DEFAULT 'Nil', "notes" text, "entry_number" integer, "is_reversed" boolean NOT NULL DEFAULT false, "reversed_by" character varying(50), "reversal_date" date, CONSTRAINT "PK_6efcb84411d3f08b08450ae75d5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_80f762cf2ae5f6c3954aa637ce" ON "ledger_entries" ("balance_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_eecef3e1e2f846c45359123ded" ON "ledger_entries" ("reference_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a8781f3c6e59c59666272e896b" ON "ledger_entries" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_150c6c74df63c1f8ccf8ee72de" ON "ledger_entries" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_24e0a5a1664a658624ef618ffc" ON "ledger_entries" ("student_id") `);
        await queryRunner.query(`CREATE TYPE "public"."discount_types_category_enum" AS ENUM('academic', 'financial_hardship', 'early_payment', 'loyalty', 'promotional', 'staff', 'sibling')`);
        await queryRunner.query(`CREATE TABLE "discount_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying(100) NOT NULL, "category" "public"."discount_types_category_enum" NOT NULL, "description" text, "default_amount" numeric(10,2), "is_percentage" boolean NOT NULL DEFAULT false, "percentage_value" numeric(5,2), "max_amount" numeric(10,2), "requires_approval" boolean NOT NULL DEFAULT false, "auto_apply" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "conditions" jsonb, CONSTRAINT "UQ_8ae159b70c815c370302910aa2b" UNIQUE ("name"), CONSTRAINT "PK_b8680bade668df47e67dcdfc93b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ab354356e0e06ac4743bf797e3" ON "discount_types" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_7b67c0e29ceb5973d9d9ce5554" ON "discount_types" ("category") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8ae159b70c815c370302910aa2" ON "discount_types" ("name") `);
        await queryRunner.query(`CREATE TYPE "public"."discounts_status_enum" AS ENUM('active', 'expired', 'cancelled', 'used')`);
        await queryRunner.query(`CREATE TYPE "public"."discounts_applied_to_enum" AS ENUM('ledger', 'invoice', 'payment')`);
        await queryRunner.query(`CREATE TABLE "discounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "student_id" uuid NOT NULL, "discount_type_id" uuid, "amount" numeric(10,2) NOT NULL, "reason" character varying(255) NOT NULL, "notes" text, "applied_by" character varying(100) NOT NULL DEFAULT 'Admin', "date" date NOT NULL, "status" "public"."discounts_status_enum" NOT NULL DEFAULT 'active', "applied_to" "public"."discounts_applied_to_enum" NOT NULL DEFAULT 'ledger', "valid_from" date, "valid_to" date, "is_percentage" boolean NOT NULL DEFAULT false, "percentage_value" numeric(5,2), "max_amount" numeric(10,2), "reference_id" character varying, CONSTRAINT "PK_66c522004212dc814d6e2f14ecc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_95542361e645fe0ebbb969ebeb" ON "discounts" ("discount_type_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3a0ddcbcaaa08786b07ac386d7" ON "discounts" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_3becbbb576ec3f7e04f9750b80" ON "discounts" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_8e2b5a5b659879e0b1f3ab7e7e" ON "discounts" ("student_id") `);
        await queryRunner.query(`CREATE TYPE "public"."student_contacts_type_enum" AS ENUM('guardian', 'emergency', 'parent', 'relative')`);
        await queryRunner.query(`CREATE TABLE "student_contacts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "student_id" uuid NOT NULL, "type" "public"."student_contacts_type_enum" NOT NULL, "name" character varying(255) NOT NULL, "phone" character varying(20) NOT NULL, "email" character varying(255), "relationship" character varying(100), "is_primary" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_63b580375d85309fd320b96f638" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_10c8e0ada8d81de0c111f4d48e" ON "student_contacts" ("student_id", "type") `);
        await queryRunner.query(`CREATE TABLE "student_academic_info" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "student_id" uuid NOT NULL, "course" character varying(255) NOT NULL, "institution" character varying(255) NOT NULL, "academic_year" character varying(20), "semester" character varying(50), "start_date" date, "expected_end_date" date, "student_id_number" character varying(100), "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_76db1cff911dd6baa8bb66587db" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2db8d2fef69571403f2e4a63f2" ON "student_academic_info" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_0c6227d20e3bd28e6756ddd279" ON "student_academic_info" ("student_id") `);
        await queryRunner.query(`CREATE TYPE "public"."student_financial_info_fee_type_enum" AS ENUM('base_monthly', 'laundry', 'food', 'utilities', 'maintenance', 'security_deposit')`);
        await queryRunner.query(`CREATE TABLE "student_financial_info" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "student_id" uuid NOT NULL, "fee_type" "public"."student_financial_info_fee_type_enum" NOT NULL, "amount" numeric(10,2) NOT NULL, "effective_from" date NOT NULL, "effective_to" date, "is_active" boolean NOT NULL DEFAULT true, "notes" text, CONSTRAINT "PK_8baa04af48cd67b754f6cb0cb30" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2077a7f7580d9e2146c70edde5" ON "student_financial_info" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_be12be3d88387a0437f7676072" ON "student_financial_info" ("student_id", "fee_type") `);
        await queryRunner.query(`CREATE TYPE "public"."students_status_enum" AS ENUM('Active', 'Inactive', 'Suspended', 'Graduated')`);
        await queryRunner.query(`CREATE TABLE "students" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying(255) NOT NULL, "phone" character varying(20) NOT NULL, "email" character varying(255) NOT NULL, "enrollment_date" date, "status" "public"."students_status_enum" NOT NULL DEFAULT 'Active', "address" text, "room_id" uuid, "booking_request_id" uuid, CONSTRAINT "UQ_317b86154bca256bdf5432f134c" UNIQUE ("phone"), CONSTRAINT "UQ_25985d58c714a4a427ced57507b" UNIQUE ("email"), CONSTRAINT "PK_7d7f07271ad4ce999880713f05e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f02c3d198bd4cfafea78366b65" ON "students" ("enrollment_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_89d97b30d7d2b126c22e4fb28d" ON "students" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_317b86154bca256bdf5432f134" ON "students" ("phone") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_25985d58c714a4a427ced57507" ON "students" ("email") `);
        await queryRunner.query(`CREATE TYPE "public"."reports_type_enum" AS ENUM('financial', 'ledger', 'payment', 'invoice', 'student', 'room', 'occupancy', 'booking')`);
        await queryRunner.query(`CREATE TYPE "public"."reports_format_enum" AS ENUM('pdf', 'excel', 'csv', 'json')`);
        await queryRunner.query(`CREATE TYPE "public"."reports_status_enum" AS ENUM('completed', 'processing', 'failed', 'queued')`);
        await queryRunner.query(`CREATE TABLE "reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying(255) NOT NULL, "type" "public"."reports_type_enum" NOT NULL, "description" text, "generated_by" character varying(100) NOT NULL, "generated_at" TIMESTAMP NOT NULL, "parameters" jsonb, "data" jsonb, "format" "public"."reports_format_enum" NOT NULL DEFAULT 'pdf', "file_path" character varying(500), "file_size" character varying(20), "status" "public"."reports_status_enum" NOT NULL DEFAULT 'completed', "is_scheduled" boolean NOT NULL DEFAULT false, "schedule_config" jsonb, "execution_time_ms" integer, "error_message" text, "download_count" integer NOT NULL DEFAULT '0', "expires_at" TIMESTAMP, CONSTRAINT "PK_d9013193989303580053c0b5ef6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a34d363c3d5ad55f27e2b37ded" ON "reports" ("is_scheduled") `);
        await queryRunner.query(`CREATE INDEX "IDX_dab4d78b3be05c1ca4a626f57f" ON "reports" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_c7b73ff3c370c4051fb0bd31bb" ON "reports" ("generated_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_9042e8a886f7f83b1de94fee28" ON "reports" ("generated_by") `);
        await queryRunner.query(`CREATE INDEX "IDX_d5e66723d29c6f38b2ba70542d" ON "reports" ("type") `);
        await queryRunner.query(`CREATE TABLE "hostel_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "hostel_name" character varying NOT NULL, "owner_name" character varying NOT NULL, "email" character varying NOT NULL, "phone" character varying NOT NULL, "address" character varying NOT NULL, "province" character varying NOT NULL, "district" character varying NOT NULL, "description" text NOT NULL, "amenities" json NOT NULL, "policies" json NOT NULL, "pricing" json NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_61c17bd646081314e8a78c332ad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."maintenance_requests_type_enum" AS ENUM('repair', 'cleaning', 'inspection', 'upgrade')`);
        await queryRunner.query(`CREATE TYPE "public"."maintenance_requests_priority_enum" AS ENUM('low', 'medium', 'high', 'urgent')`);
        await queryRunner.query(`CREATE TYPE "public"."maintenance_requests_status_enum" AS ENUM('pending', 'in-progress', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "maintenance_requests" ("id" SERIAL NOT NULL, "room_id" character varying NOT NULL, "title" character varying NOT NULL, "description" text NOT NULL, "type" "public"."maintenance_requests_type_enum" NOT NULL DEFAULT 'repair', "priority" "public"."maintenance_requests_priority_enum" NOT NULL DEFAULT 'medium', "status" "public"."maintenance_requests_status_enum" NOT NULL DEFAULT 'pending', "reported_by" character varying NOT NULL, "assigned_to" character varying, "reported_at" TIMESTAMP NOT NULL, "scheduled_at" TIMESTAMP, "completed_at" TIMESTAMP, "cost" numeric(10,2) NOT NULL DEFAULT '0', "notes" text, "images" json, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c1521eb67c471accae8c531f9fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_recipient_type_enum" AS ENUM('student', 'staff', 'all')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('info', 'success', 'warning', 'error')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_category_enum" AS ENUM('billing', 'maintenance', 'general', 'reports', 'system', 'booking', 'security', 'inventory', 'events')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_priority_enum" AS ENUM('low', 'medium', 'high')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" SERIAL NOT NULL, "recipient_id" character varying, "recipient_type" "public"."notifications_recipient_type_enum" NOT NULL, "title" character varying NOT NULL, "message" text NOT NULL, "type" "public"."notifications_type_enum" NOT NULL DEFAULT 'info', "category" "public"."notifications_category_enum" NOT NULL DEFAULT 'general', "priority" "public"."notifications_priority_enum" NOT NULL DEFAULT 'medium', "is_read" boolean NOT NULL DEFAULT false, "sent_at" TIMESTAMP NOT NULL, "read_at" TIMESTAMP, "action_url" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "room_amenities" ADD CONSTRAINT "FK_1bbdd33b01f2e52f4dd50743544" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_amenities" ADD CONSTRAINT "FK_936612d991e2522e82cd86fa106" FOREIGN KEY ("amenity_id") REFERENCES "amenities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_occupants" ADD CONSTRAINT "FK_cf232404b982f258b00a672f101" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_occupants" ADD CONSTRAINT "FK_a425cdf454f2ecbcec3f1139ec8" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_layouts" ADD CONSTRAINT "FK_6c9f060b1d7c9756a8b60a6a614" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD CONSTRAINT "FK_0390a2fda90b13e8f578ff920c1" FOREIGN KEY ("buildingId") REFERENCES "buildings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD CONSTRAINT "FK_76b20e23154532d6fc4a0f0ea27" FOREIGN KEY ("roomTypeId") REFERENCES "room_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD CONSTRAINT "FK_dc991d555664682cfe892eea2c1" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_9fd5d6ef620b0140a67ff2d95c4" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_invoice_allocations" ADD CONSTRAINT "FK_76537e5e10deb46e527c75af62a" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_invoice_allocations" ADD CONSTRAINT "FK_b5a8a2c5db43abdee5ce5f1441b" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_0a19069218ffe36a4e4b41c4870" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ledger_entries" ADD CONSTRAINT "FK_24e0a5a1664a658624ef618ffcc" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discounts" ADD CONSTRAINT "FK_8e2b5a5b659879e0b1f3ab7e7e9" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discounts" ADD CONSTRAINT "FK_95542361e645fe0ebbb969ebeb9" FOREIGN KEY ("discount_type_id") REFERENCES "discount_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_contacts" ADD CONSTRAINT "FK_0c3cdd27069e42ad422cbcd28dc" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_academic_info" ADD CONSTRAINT "FK_0c6227d20e3bd28e6756ddd2798" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_financial_info" ADD CONSTRAINT "FK_d675662dc0ea4596aee5b854563" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_f8c241265ea322470a2897ce0cd" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_936bc6419c1635ce60ad6e6401e" FOREIGN KEY ("booking_request_id") REFERENCES "booking_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_936bc6419c1635ce60ad6e6401e"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_f8c241265ea322470a2897ce0cd"`);
        await queryRunner.query(`ALTER TABLE "student_financial_info" DROP CONSTRAINT "FK_d675662dc0ea4596aee5b854563"`);
        await queryRunner.query(`ALTER TABLE "student_academic_info" DROP CONSTRAINT "FK_0c6227d20e3bd28e6756ddd2798"`);
        await queryRunner.query(`ALTER TABLE "student_contacts" DROP CONSTRAINT "FK_0c3cdd27069e42ad422cbcd28dc"`);
        await queryRunner.query(`ALTER TABLE "discounts" DROP CONSTRAINT "FK_95542361e645fe0ebbb969ebeb9"`);
        await queryRunner.query(`ALTER TABLE "discounts" DROP CONSTRAINT "FK_8e2b5a5b659879e0b1f3ab7e7e9"`);
        await queryRunner.query(`ALTER TABLE "ledger_entries" DROP CONSTRAINT "FK_24e0a5a1664a658624ef618ffcc"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_0a19069218ffe36a4e4b41c4870"`);
        await queryRunner.query(`ALTER TABLE "payment_invoice_allocations" DROP CONSTRAINT "FK_b5a8a2c5db43abdee5ce5f1441b"`);
        await queryRunner.query(`ALTER TABLE "payment_invoice_allocations" DROP CONSTRAINT "FK_76537e5e10deb46e527c75af62a"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_9fd5d6ef620b0140a67ff2d95c4"`);
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP CONSTRAINT "FK_dc991d555664682cfe892eea2c1"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP CONSTRAINT "FK_76b20e23154532d6fc4a0f0ea27"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP CONSTRAINT "FK_0390a2fda90b13e8f578ff920c1"`);
        await queryRunner.query(`ALTER TABLE "room_layouts" DROP CONSTRAINT "FK_6c9f060b1d7c9756a8b60a6a614"`);
        await queryRunner.query(`ALTER TABLE "room_occupants" DROP CONSTRAINT "FK_a425cdf454f2ecbcec3f1139ec8"`);
        await queryRunner.query(`ALTER TABLE "room_occupants" DROP CONSTRAINT "FK_cf232404b982f258b00a672f101"`);
        await queryRunner.query(`ALTER TABLE "room_amenities" DROP CONSTRAINT "FK_936612d991e2522e82cd86fa106"`);
        await queryRunner.query(`ALTER TABLE "room_amenities" DROP CONSTRAINT "FK_1bbdd33b01f2e52f4dd50743544"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_recipient_type_enum"`);
        await queryRunner.query(`DROP TABLE "maintenance_requests"`);
        await queryRunner.query(`DROP TYPE "public"."maintenance_requests_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."maintenance_requests_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."maintenance_requests_type_enum"`);
        await queryRunner.query(`DROP TABLE "hostel_profiles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d5e66723d29c6f38b2ba70542d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9042e8a886f7f83b1de94fee28"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c7b73ff3c370c4051fb0bd31bb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dab4d78b3be05c1ca4a626f57f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a34d363c3d5ad55f27e2b37ded"`);
        await queryRunner.query(`DROP TABLE "reports"`);
        await queryRunner.query(`DROP TYPE "public"."reports_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."reports_format_enum"`);
        await queryRunner.query(`DROP TYPE "public"."reports_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_25985d58c714a4a427ced57507"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_317b86154bca256bdf5432f134"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_89d97b30d7d2b126c22e4fb28d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f02c3d198bd4cfafea78366b65"`);
        await queryRunner.query(`DROP TABLE "students"`);
        await queryRunner.query(`DROP TYPE "public"."students_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_be12be3d88387a0437f7676072"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2077a7f7580d9e2146c70edde5"`);
        await queryRunner.query(`DROP TABLE "student_financial_info"`);
        await queryRunner.query(`DROP TYPE "public"."student_financial_info_fee_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0c6227d20e3bd28e6756ddd279"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2db8d2fef69571403f2e4a63f2"`);
        await queryRunner.query(`DROP TABLE "student_academic_info"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_10c8e0ada8d81de0c111f4d48e"`);
        await queryRunner.query(`DROP TABLE "student_contacts"`);
        await queryRunner.query(`DROP TYPE "public"."student_contacts_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8e2b5a5b659879e0b1f3ab7e7e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3becbbb576ec3f7e04f9750b80"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3a0ddcbcaaa08786b07ac386d7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_95542361e645fe0ebbb969ebeb"`);
        await queryRunner.query(`DROP TABLE "discounts"`);
        await queryRunner.query(`DROP TYPE "public"."discounts_applied_to_enum"`);
        await queryRunner.query(`DROP TYPE "public"."discounts_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8ae159b70c815c370302910aa2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7b67c0e29ceb5973d9d9ce5554"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ab354356e0e06ac4743bf797e3"`);
        await queryRunner.query(`DROP TABLE "discount_types"`);
        await queryRunner.query(`DROP TYPE "public"."discount_types_category_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_24e0a5a1664a658624ef618ffc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_150c6c74df63c1f8ccf8ee72de"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a8781f3c6e59c59666272e896b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eecef3e1e2f846c45359123ded"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_80f762cf2ae5f6c3954aa637ce"`);
        await queryRunner.query(`DROP TABLE "ledger_entries"`);
        await queryRunner.query(`DROP TYPE "public"."ledger_entries_balance_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."ledger_entries_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0a19069218ffe36a4e4b41c487"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e1ba9929f00a8e2ee0ca1e30b8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac0f09364e3701d9ed35435288"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0457ee681a50419881ea2ee796"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_adac6477f8ae75b75d47d77279"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_76537e5e10deb46e527c75af62"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b5a8a2c5db43abdee5ce5f1441"`);
        await queryRunner.query(`DROP TABLE "payment_invoice_allocations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9fd5d6ef620b0140a67ff2d95c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_685fffacc6464277439d0260ab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f65f62084af2ebfbe39f8955b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32b41cdb985a296213e9a928b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_28a497308e609408717dadf192"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_payment_method_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dc991d555664682cfe892eea2c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2a6bd669a5ce3579b7f751afb9"`);
        await queryRunner.query(`DROP TABLE "invoice_items"`);
        await queryRunner.query(`DROP TYPE "public"."invoice_items_category_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_820acb1f1d89fd9085a4204274"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0567a1c8478376a332de21ef4e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c2e6a2eac7e1f90103491f3001"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_edc5f87424722536e690051bd5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_74e588ac3c9e2ac2a5b557cfaa"`);
        await queryRunner.query(`DROP TABLE "booking_requests"`);
        await queryRunner.query(`DROP TYPE "public"."booking_requests_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e38efca75345af077ed83d53b6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ffd12d5e703ed4027ebd41df44"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0390a2fda90b13e8f578ff920c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_76b20e23154532d6fc4a0f0ea2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ed601f2a18a58e7bb5093ce7e3"`);
        await queryRunner.query(`DROP TABLE "rooms"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_20180102ff8f034e54c5812f69"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5457ff4ea3051ac9ad68969f5f"`);
        await queryRunner.query(`DROP TABLE "room_types"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f5a7e0aabca27edc3806fdb29"`);
        await queryRunner.query(`DROP TABLE "buildings"`);
        await queryRunner.query(`DROP TABLE "room_layouts"`);
        await queryRunner.query(`DROP TABLE "room_occupants"`);
        await queryRunner.query(`DROP TABLE "room_amenities"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c5f9c7ff7e2174b53d4be1024"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1310fb8b8ec62a1f5292f49e1b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8020b0d3a0e19f06464c2a9d0b"`);
        await queryRunner.query(`DROP TABLE "amenities"`);
    }

}
