import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateBookingGuestBedNumberLength1757017238354 implements MigrationInterface {
    name = 'UpdateBookingGuestBedNumberLength1757017238354'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "beds" DROP CONSTRAINT "FK_beds_room_id"`);
        await queryRunner.query(`ALTER TABLE "admin_charges" DROP CONSTRAINT "FK_admin_charges_student_id"`);
        await queryRunner.query(`ALTER TABLE "booking_guests" DROP CONSTRAINT "fk_booking_guests_booking_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_beds_room_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_beds_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_beds_bed_identifier"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_beds_bed_number"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_beds_gender"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_admin_charges_student_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_admin_charges_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_admin_charges_charge_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_admin_charges_due_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_admin_charges_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_booking_guests_booking_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_booking_guests_bed_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_booking_guests_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_booking_guests_gender"`);
        await queryRunner.query(`DROP INDEX "public"."idx_multi_guest_bookings_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_multi_guest_bookings_contact_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_multi_guest_bookings_contact_phone"`);
        await queryRunner.query(`DROP INDEX "public"."idx_multi_guest_bookings_check_in_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e1ba9929f00a8e2ee0ca1e30b8"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "month"`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "month" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."invoices_status_enum" RENAME TO "invoices_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('Paid', 'Unpaid', 'Partially Paid', 'Overdue', 'Cancelled', 'Sent')`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" TYPE "public"."invoices_status_enum" USING "status"::"text"::"public"."invoices_status_enum"`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" SET DEFAULT 'Unpaid'`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "students" DROP COLUMN "bed_number"`);
        await queryRunner.query(`ALTER TABLE "students" ADD "bed_number" character varying`);
        await queryRunner.query(`ALTER TYPE "public"."guest_status_enum" RENAME TO "guest_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."booking_guests_status_enum" AS ENUM('Pending', 'Confirmed', 'Checked_In', 'Checked_Out', 'Cancelled')`);
        await queryRunner.query(`ALTER TABLE "booking_guests" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "booking_guests" ALTER COLUMN "status" TYPE "public"."booking_guests_status_enum" USING "status"::"text"::"public"."booking_guests_status_enum"`);
        await queryRunner.query(`ALTER TABLE "booking_guests" ALTER COLUMN "status" SET DEFAULT 'Pending'`);
        await queryRunner.query(`DROP TYPE "public"."guest_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "booking_guests" DROP COLUMN "assigned_bed_number"`);
        await queryRunner.query(`ALTER TABLE "booking_guests" ADD "assigned_bed_number" character varying(50)`);
        await queryRunner.query(`ALTER TYPE "public"."multi_guest_booking_status_enum" RENAME TO "multi_guest_booking_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."multi_guest_bookings_status_enum" AS ENUM('Pending', 'Confirmed', 'Partially_Confirmed', 'Cancelled', 'Completed')`);
        await queryRunner.query(`ALTER TABLE "multi_guest_bookings" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "multi_guest_bookings" ALTER COLUMN "status" TYPE "public"."multi_guest_bookings_status_enum" USING "status"::"text"::"public"."multi_guest_bookings_status_enum"`);
        await queryRunner.query(`ALTER TABLE "multi_guest_bookings" ALTER COLUMN "status" SET DEFAULT 'Pending'`);
        await queryRunner.query(`DROP TYPE "public"."multi_guest_booking_status_enum_old"`);
        await queryRunner.query(`CREATE INDEX "IDX_af2718efefbfba955c4d54d7a0" ON "beds" ("gender") `);
        await queryRunner.query(`CREATE INDEX "IDX_c46d75b9e74e7f7f6c2046d0bb" ON "beds" ("bed_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_c11721ca6ca7c067ceb3b92fa0" ON "beds" ("bed_identifier") `);
        await queryRunner.query(`CREATE INDEX "IDX_d779b19f2bd74ca3c9a18c0df9" ON "beds" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_fd7413faee42749f1b2e827039" ON "beds" ("room_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e1ba9929f00a8e2ee0ca1e30b8" ON "invoices" ("month") `);
        await queryRunner.query(`CREATE INDEX "IDX_7ffe4fb213fe098220d7448d5c" ON "admin_charges" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_7e48de58077fad71559a3f2bc6" ON "admin_charges" ("due_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_e4dfd53093f0e681ef3752bf3c" ON "admin_charges" ("charge_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_eb82ca37eabbcb3d43934e259f" ON "admin_charges" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_5f3625a8093fd82988760162ab" ON "admin_charges" ("student_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6e08c54ab63e4d1e2f1f2966c6" ON "booking_guests" ("gender") `);
        await queryRunner.query(`CREATE INDEX "IDX_7c86a70ce8bff8e693c05290c1" ON "booking_guests" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_8f96fdf67be035a1163299668b" ON "booking_guests" ("bed_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5220a9b1a76915eedc5cb9fe52" ON "booking_guests" ("booking_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5d0b708b471be477026e80dd42" ON "multi_guest_bookings" ("check_in_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_d11c15f3e3ebfc3850a4f9ee4d" ON "multi_guest_bookings" ("contact_phone") `);
        await queryRunner.query(`CREATE INDEX "IDX_c047035747e74f52ef4e6cbd11" ON "multi_guest_bookings" ("contact_email") `);
        await queryRunner.query(`CREATE INDEX "IDX_26ba271999244258cf9fbc66e4" ON "multi_guest_bookings" ("status") `);
        await queryRunner.query(`ALTER TABLE "beds" ADD CONSTRAINT "FK_fd7413faee42749f1b2e8270394" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_charges" ADD CONSTRAINT "FK_5f3625a8093fd82988760162abd" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_guests" ADD CONSTRAINT "FK_5220a9b1a76915eedc5cb9fe526" FOREIGN KEY ("booking_id") REFERENCES "multi_guest_bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "booking_guests" DROP CONSTRAINT "FK_5220a9b1a76915eedc5cb9fe526"`);
        await queryRunner.query(`ALTER TABLE "admin_charges" DROP CONSTRAINT "FK_5f3625a8093fd82988760162abd"`);
        await queryRunner.query(`ALTER TABLE "beds" DROP CONSTRAINT "FK_fd7413faee42749f1b2e8270394"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_26ba271999244258cf9fbc66e4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c047035747e74f52ef4e6cbd11"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d11c15f3e3ebfc3850a4f9ee4d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5d0b708b471be477026e80dd42"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5220a9b1a76915eedc5cb9fe52"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8f96fdf67be035a1163299668b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7c86a70ce8bff8e693c05290c1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e08c54ab63e4d1e2f1f2966c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f3625a8093fd82988760162ab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eb82ca37eabbcb3d43934e259f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e4dfd53093f0e681ef3752bf3c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e48de58077fad71559a3f2bc6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7ffe4fb213fe098220d7448d5c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e1ba9929f00a8e2ee0ca1e30b8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fd7413faee42749f1b2e827039"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d779b19f2bd74ca3c9a18c0df9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c11721ca6ca7c067ceb3b92fa0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c46d75b9e74e7f7f6c2046d0bb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af2718efefbfba955c4d54d7a0"`);
        await queryRunner.query(`CREATE TYPE "public"."multi_guest_booking_status_enum_old" AS ENUM('Pending', 'Confirmed', 'Partially_Confirmed', 'Cancelled', 'Completed')`);
        await queryRunner.query(`ALTER TABLE "multi_guest_bookings" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "multi_guest_bookings" ALTER COLUMN "status" TYPE "public"."multi_guest_booking_status_enum_old" USING "status"::"text"::"public"."multi_guest_booking_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "multi_guest_bookings" ALTER COLUMN "status" SET DEFAULT 'Pending'`);
        await queryRunner.query(`DROP TYPE "public"."multi_guest_bookings_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."multi_guest_booking_status_enum_old" RENAME TO "multi_guest_booking_status_enum"`);
        await queryRunner.query(`ALTER TABLE "booking_guests" DROP COLUMN "assigned_bed_number"`);
        await queryRunner.query(`ALTER TABLE "booking_guests" ADD "assigned_bed_number" character varying(10)`);
        await queryRunner.query(`CREATE TYPE "public"."guest_status_enum_old" AS ENUM('Pending', 'Confirmed', 'Checked_In', 'Checked_Out', 'Cancelled')`);
        await queryRunner.query(`ALTER TABLE "booking_guests" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "booking_guests" ALTER COLUMN "status" TYPE "public"."guest_status_enum_old" USING "status"::"text"::"public"."guest_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "booking_guests" ALTER COLUMN "status" SET DEFAULT 'Pending'`);
        await queryRunner.query(`DROP TYPE "public"."booking_guests_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."guest_status_enum_old" RENAME TO "guest_status_enum"`);
        await queryRunner.query(`ALTER TABLE "students" DROP COLUMN "bed_number"`);
        await queryRunner.query(`ALTER TABLE "students" ADD "bed_number" character varying(50)`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum_old" AS ENUM('Paid', 'Unpaid', 'Partially Paid', 'Overdue', 'Cancelled')`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" TYPE "public"."invoices_status_enum_old" USING "status"::"text"::"public"."invoices_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" SET DEFAULT 'Unpaid'`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."invoices_status_enum_old" RENAME TO "invoices_status_enum"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "month"`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "month" character varying(7) NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_e1ba9929f00a8e2ee0ca1e30b8" ON "invoices" ("month") `);
        await queryRunner.query(`CREATE INDEX "idx_multi_guest_bookings_check_in_date" ON "multi_guest_bookings" ("check_in_date") `);
        await queryRunner.query(`CREATE INDEX "idx_multi_guest_bookings_contact_phone" ON "multi_guest_bookings" ("contact_phone") `);
        await queryRunner.query(`CREATE INDEX "idx_multi_guest_bookings_contact_email" ON "multi_guest_bookings" ("contact_email") `);
        await queryRunner.query(`CREATE INDEX "idx_multi_guest_bookings_status" ON "multi_guest_bookings" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_booking_guests_gender" ON "booking_guests" ("gender") `);
        await queryRunner.query(`CREATE INDEX "idx_booking_guests_status" ON "booking_guests" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_booking_guests_bed_id" ON "booking_guests" ("bed_id") `);
        await queryRunner.query(`CREATE INDEX "idx_booking_guests_booking_id" ON "booking_guests" ("booking_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_admin_charges_created_at" ON "admin_charges" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_admin_charges_due_date" ON "admin_charges" ("due_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_admin_charges_charge_type" ON "admin_charges" ("charge_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_admin_charges_status" ON "admin_charges" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_admin_charges_student_id" ON "admin_charges" ("student_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_beds_gender" ON "beds" ("gender") `);
        await queryRunner.query(`CREATE INDEX "IDX_beds_bed_number" ON "beds" ("bed_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_beds_bed_identifier" ON "beds" ("bed_identifier") `);
        await queryRunner.query(`CREATE INDEX "IDX_beds_status" ON "beds" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_beds_room_id" ON "beds" ("room_id") `);
        await queryRunner.query(`ALTER TABLE "booking_guests" ADD CONSTRAINT "fk_booking_guests_booking_id" FOREIGN KEY ("booking_id") REFERENCES "multi_guest_bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_charges" ADD CONSTRAINT "FK_admin_charges_student_id" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "beds" ADD CONSTRAINT "FK_beds_room_id" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
