import { IsString, IsNumber, IsOptional, IsEnum, IsDateString, IsArray, ValidateNested } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import { InvoiceStatus } from '../entities/invoice.entity';

export class CreateInvoiceItemDto {
  @ApiProperty({ description: 'Item description' })
  @IsString()
  description: string;

  @ApiProperty({ description: 'Item amount' })
  @IsNumber()
  amount: number;

  @ApiProperty({ description: 'Item category', required: false })
  @IsOptional()
  @IsString()
  category?: string;

  @ApiProperty({ description: 'Item quantity', required: false })
  @IsOptional()
  @IsNumber()
  quantity?: number;

  @ApiProperty({ description: 'Unit price', required: false })
  @IsOptional()
  @IsNumber()
  unitPrice?: number;
}

export class CreateInvoiceDto {
  @ApiProperty({ description: 'Student ID' })
  @IsString()
  studentId: string;

  @ApiProperty({ description: 'Invoice month (e.g., "January 2024")' })
  @IsString()
  month: string;

  @ApiProperty({ description: 'Invoice total amount' })
  @IsNumber()
  total: number;

  @ApiProperty({ description: 'Invoice status', enum: InvoiceStatus, required: false })
  @IsOptional()
  @IsEnum(InvoiceStatus)
  status?: InvoiceStatus;

  @ApiProperty({ description: 'Due date' })
  @IsDateString()
  dueDate: Date;

  @ApiProperty({ description: 'Subtotal amount', required: false })
  @IsOptional()
  @IsNumber()
  subtotal?: number;

  @ApiProperty({ description: 'Total discount amount', required: false })
  @IsOptional()
  @IsNumber()
  discountTotal?: number;

  @ApiProperty({ description: 'Total payment amount', required: false })
  @IsOptional()
  @IsNumber()
  paymentTotal?: number;

  @ApiProperty({ description: 'Invoice notes', required: false })
  @IsOptional()
  @IsString()
  notes?: string;

  @ApiProperty({ description: 'Invoice number', required: false })
  @IsOptional()
  @IsString()
  invoiceNumber?: string;

  @ApiProperty({ description: 'Generated by', required: false })
  @IsOptional()
  @IsString()
  generatedBy?: string;

  @ApiProperty({ description: 'Invoice items', type: [CreateInvoiceItemDto], required: false })
  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => CreateInvoiceItemDto)
  items?: CreateInvoiceItemDto[];
}