import { MigrationInterface, QueryRunner } from "typeorm";

export class AddImagesToRooms1758181596083 implements MigrationInterface {
    name = 'AddImagesToRooms1758181596083'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "beds" DROP CONSTRAINT "FK_beds_hostelId"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP CONSTRAINT "FK_rooms_hostelId"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_payments_hostelId"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_invoices_hostelId"`);
        await queryRunner.query(`ALTER TABLE "ledger_entries" DROP CONSTRAINT "FK_ledger_entries_hostelId"`);
        await queryRunner.query(`ALTER TABLE "discounts" DROP CONSTRAINT "FK_discounts_hostelId"`);
        await queryRunner.query(`ALTER TABLE "admin_charges" DROP CONSTRAINT "FK_admin_charges_hostelId"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_students_hostelId"`);
        await queryRunner.query(`ALTER TABLE "booking_guests" DROP CONSTRAINT "FK_booking_guests_bed_id"`);
        await queryRunner.query(`ALTER TABLE "multi_guest_bookings" DROP CONSTRAINT "FK_multi_guest_bookings_hostelId"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_reports_hostelId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_beds_hostelId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_rooms_hostelId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_hostelId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoices_hostelId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ledger_entries_hostelId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_discounts_hostelId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_admin_charges_hostelId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_students_hostelId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_booking_guests_booking_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_booking_guests_gender"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_booking_guests_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_booking_guests_bed_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_multi_guest_bookings_contact_email"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_multi_guest_bookings_contact_phone"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_multi_guest_bookings_check_in_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_multi_guest_bookings_request_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_multi_guest_bookings_priority_score"`);
        await queryRunner.query(`DROP INDEX "public"."idx_multi_guest_bookings_source"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_multi_guest_bookings_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_multi_guest_bookings_hostelId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_multi_guest_bookings_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_reports_hostelId"`);
        await queryRunner.query(`ALTER TABLE "hostel_profiles" DROP COLUMN "owner_name"`);
        await queryRunner.query(`ALTER TABLE "hostel_profiles" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "hostel_profiles" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "hostel_profiles" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "hostel_profiles" DROP COLUMN "province"`);
        await queryRunner.query(`ALTER TABLE "hostel_profiles" DROP COLUMN "district"`);
        await queryRunner.query(`ALTER TABLE "hostel_profiles" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "hostel_profiles" DROP COLUMN "amenities"`);
        await queryRunner.query(`ALTER TABLE "hostel_profiles" DROP COLUMN "policies"`);
        await queryRunner.query(`ALTER TABLE "hostel_profiles" DROP COLUMN "pricing"`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD "images" json`);
        await queryRunner.query(`ALTER TABLE "hostel_profiles" DROP COLUMN "hostel_name"`);
        await queryRunner.query(`ALTER TABLE "hostel_profiles" ADD "hostel_name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "multi_guest_bookings" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "multi_guest_bookings" ADD "user_id" character varying`);
        await queryRunner.query(`ALTER TABLE "multi_guest_bookings" ALTER COLUMN "request_date" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "multi_guest_bookings" ALTER COLUMN "request_date" DROP DEFAULT`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4f9b62d34d3e86660f4f2b70a3" ON "hostel_profiles" ("business_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0bf377ee55757fa1d90a0109e1" ON "beds" ("hostelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7ea81bd15cff0b6a7a50814095" ON "rooms" ("hostelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e7132d7897ec738d8ef7b71aaa" ON "payments" ("hostelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_188421abe7b832dbb61e5ab414" ON "invoices" ("hostelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a35496b0d4e93bb75599838280" ON "ledger_entries" ("hostelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_28b8f05c94697684d145d5c250" ON "discounts" ("hostelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a5c13dac52f98610056f1d156e" ON "admin_charges" ("hostelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3a4d21c18539d764cddd76e8be" ON "students" ("hostelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_78f9ac3a0a1d346d3d3e4f67d1" ON "multi_guest_bookings" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_05d1df436632dc19446274b6a6" ON "multi_guest_bookings" ("hostelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b0158200aebb4c7e89a2f82844" ON "reports" ("hostelId") `);
        await queryRunner.query(`ALTER TABLE "beds" ADD CONSTRAINT "FK_0bf377ee55757fa1d90a0109e1c" FOREIGN KEY ("hostelId") REFERENCES "hostel_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD CONSTRAINT "FK_7ea81bd15cff0b6a7a50814095b" FOREIGN KEY ("hostelId") REFERENCES "hostel_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_e7132d7897ec738d8ef7b71aaae" FOREIGN KEY ("hostelId") REFERENCES "hostel_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_188421abe7b832dbb61e5ab4149" FOREIGN KEY ("hostelId") REFERENCES "hostel_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ledger_entries" ADD CONSTRAINT "FK_a35496b0d4e93bb755998382800" FOREIGN KEY ("hostelId") REFERENCES "hostel_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discounts" ADD CONSTRAINT "FK_28b8f05c94697684d145d5c2505" FOREIGN KEY ("hostelId") REFERENCES "hostel_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_charges" ADD CONSTRAINT "FK_a5c13dac52f98610056f1d156e3" FOREIGN KEY ("hostelId") REFERENCES "hostel_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_3a4d21c18539d764cddd76e8be3" FOREIGN KEY ("hostelId") REFERENCES "hostel_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_guests" ADD CONSTRAINT "FK_8f96fdf67be035a1163299668b5" FOREIGN KEY ("bed_id") REFERENCES "beds"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "multi_guest_bookings" ADD CONSTRAINT "FK_05d1df436632dc19446274b6a6b" FOREIGN KEY ("hostelId") REFERENCES "hostel_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_b0158200aebb4c7e89a2f828448" FOREIGN KEY ("hostelId") REFERENCES "hostel_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_b0158200aebb4c7e89a2f828448"`);
        await queryRunner.query(`ALTER TABLE "multi_guest_bookings" DROP CONSTRAINT "FK_05d1df436632dc19446274b6a6b"`);
        await queryRunner.query(`ALTER TABLE "booking_guests" DROP CONSTRAINT "FK_8f96fdf67be035a1163299668b5"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_3a4d21c18539d764cddd76e8be3"`);
        await queryRunner.query(`ALTER TABLE "admin_charges" DROP CONSTRAINT "FK_a5c13dac52f98610056f1d156e3"`);
        await queryRunner.query(`ALTER TABLE "discounts" DROP CONSTRAINT "FK_28b8f05c94697684d145d5c2505"`);
        await queryRunner.query(`ALTER TABLE "ledger_entries" DROP CONSTRAINT "FK_a35496b0d4e93bb755998382800"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_188421abe7b832dbb61e5ab4149"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_e7132d7897ec738d8ef7b71aaae"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP CONSTRAINT "FK_7ea81bd15cff0b6a7a50814095b"`);
        await queryRunner.query(`ALTER TABLE "beds" DROP CONSTRAINT "FK_0bf377ee55757fa1d90a0109e1c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b0158200aebb4c7e89a2f82844"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_05d1df436632dc19446274b6a6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78f9ac3a0a1d346d3d3e4f67d1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3a4d21c18539d764cddd76e8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a5c13dac52f98610056f1d156e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_28b8f05c94697684d145d5c250"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a35496b0d4e93bb75599838280"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_188421abe7b832dbb61e5ab414"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e7132d7897ec738d8ef7b71aaa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7ea81bd15cff0b6a7a50814095"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0bf377ee55757fa1d90a0109e1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4f9b62d34d3e86660f4f2b70a3"`);
        await queryRunner.query(`ALTER TABLE "multi_guest_bookings" ALTER COLUMN "request_date" SET DEFAULT CURRENT_DATE`);
        await queryRunner.query(`ALTER TABLE "multi_guest_bookings" ALTER COLUMN "request_date" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "multi_guest_bookings" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "multi_guest_bookings" ADD "user_id" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "hostel_profiles" DROP COLUMN "hostel_name"`);
        await queryRunner.query(`ALTER TABLE "hostel_profiles" ADD "hostel_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP COLUMN "images"`);
        await queryRunner.query(`ALTER TABLE "hostel_profiles" ADD "pricing" json`);
        await queryRunner.query(`ALTER TABLE "hostel_profiles" ADD "policies" json`);
        await queryRunner.query(`ALTER TABLE "hostel_profiles" ADD "amenities" json`);
        await queryRunner.query(`ALTER TABLE "hostel_profiles" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "hostel_profiles" ADD "district" character varying`);
        await queryRunner.query(`ALTER TABLE "hostel_profiles" ADD "province" character varying`);
        await queryRunner.query(`ALTER TABLE "hostel_profiles" ADD "address" character varying`);
        await queryRunner.query(`ALTER TABLE "hostel_profiles" ADD "phone" character varying`);
        await queryRunner.query(`ALTER TABLE "hostel_profiles" ADD "email" character varying`);
        await queryRunner.query(`ALTER TABLE "hostel_profiles" ADD "owner_name" character varying`);
        await queryRunner.query(`CREATE INDEX "IDX_reports_hostelId" ON "reports" ("hostelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_multi_guest_bookings_user_id" ON "multi_guest_bookings" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_multi_guest_bookings_hostelId" ON "multi_guest_bookings" ("hostelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_multi_guest_bookings_status" ON "multi_guest_bookings" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_multi_guest_bookings_source" ON "multi_guest_bookings" ("source") `);
        await queryRunner.query(`CREATE INDEX "idx_multi_guest_bookings_priority_score" ON "multi_guest_bookings" ("priority_score") `);
        await queryRunner.query(`CREATE INDEX "idx_multi_guest_bookings_request_date" ON "multi_guest_bookings" ("request_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_multi_guest_bookings_check_in_date" ON "multi_guest_bookings" ("check_in_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_multi_guest_bookings_contact_phone" ON "multi_guest_bookings" ("contact_phone") `);
        await queryRunner.query(`CREATE INDEX "IDX_multi_guest_bookings_contact_email" ON "multi_guest_bookings" ("contact_email") `);
        await queryRunner.query(`CREATE INDEX "IDX_booking_guests_bed_id" ON "booking_guests" ("bed_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_booking_guests_status" ON "booking_guests" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_booking_guests_gender" ON "booking_guests" ("gender") `);
        await queryRunner.query(`CREATE INDEX "IDX_booking_guests_booking_id" ON "booking_guests" ("booking_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_students_hostelId" ON "students" ("hostelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_admin_charges_hostelId" ON "admin_charges" ("hostelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_discounts_hostelId" ON "discounts" ("hostelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ledger_entries_hostelId" ON "ledger_entries" ("hostelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_invoices_hostelId" ON "invoices" ("hostelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_hostelId" ON "payments" ("hostelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_rooms_hostelId" ON "rooms" ("hostelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_beds_hostelId" ON "beds" ("hostelId") `);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_reports_hostelId" FOREIGN KEY ("hostelId") REFERENCES "hostel_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "multi_guest_bookings" ADD CONSTRAINT "FK_multi_guest_bookings_hostelId" FOREIGN KEY ("hostelId") REFERENCES "hostel_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "booking_guests" ADD CONSTRAINT "FK_booking_guests_bed_id" FOREIGN KEY ("bed_id") REFERENCES "beds"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_students_hostelId" FOREIGN KEY ("hostelId") REFERENCES "hostel_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "admin_charges" ADD CONSTRAINT "FK_admin_charges_hostelId" FOREIGN KEY ("hostelId") REFERENCES "hostel_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "discounts" ADD CONSTRAINT "FK_discounts_hostelId" FOREIGN KEY ("hostelId") REFERENCES "hostel_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ledger_entries" ADD CONSTRAINT "FK_ledger_entries_hostelId" FOREIGN KEY ("hostelId") REFERENCES "hostel_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_invoices_hostelId" FOREIGN KEY ("hostelId") REFERENCES "hostel_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_payments_hostelId" FOREIGN KEY ("hostelId") REFERENCES "hostel_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD CONSTRAINT "FK_rooms_hostelId" FOREIGN KEY ("hostelId") REFERENCES "hostel_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "beds" ADD CONSTRAINT "FK_beds_hostelId" FOREIGN KEY ("hostelId") REFERENCES "hostel_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
    }

}
